# Generated by Django 3.1 on 2020-10-31 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0002_addwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('user', models.CharField(max_length=120)),
                ('userskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeapp.skill')),
            ],
        ),
    ]
