# Generated by Django 3.1 on 2020-10-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0003_userskillmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addskill',
            name='location',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
    ]
