# Generated by Django 3.1 on 2020-10-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0004_addskill_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSkillModel',
        ),
    ]
