# Generated by Django 3.1 on 2020-10-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0005_delete_userskillmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addskill',
            old_name='skill',
            new_name='skillname',
        ),
    ]
