# Generated by Django 3.1 on 2020-10-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0006_auto_20201031_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addskill',
            old_name='skillname',
            new_name='userskill',
        ),
    ]
