# Generated by Django 3.1 on 2020-11-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0007_auto_20201031_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NegotiablePrice', models.IntegerField()),
                ('ExpectedDays', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('workid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeapp.addwork')),
            ],
        ),
    ]
